# Site settings
title: Mohammad Parvin
description: 'Business Card Page'
url: 'https://mparvin.me'
baseurl: ''
profilepic: '/images/mparvin.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-114794438-1
font_awesome: '53d7a3a62b.js'

author:
  name: 'Mohammad Parvin'
  email: me@mparvin.me
  twitter_username: mparvin
#  facebook_username: joshgerdes
  github_username:  MParvin
  linkedin_username:  MParvin
  meetup_name: mparvin

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
